feat: adding github corners component
Nick-Gabe/nick-tech-posts pull request #18
Opened 2023-05-04 05:58 UTC by barbosadev

2023-05-04 11:27 UTC, Nick-Gabe commented
Opa, valeu pelo PR amigo :)

Mas rolou um erro por aqui:
```
[08:21:51] ReferenceError: document is not defined
[08:21:51]     at 48357 (/vercel/path0/.next/server/chunks/550.js:186369:33)
[08:21:51]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[08:21:51]     at 32341 (/vercel/path0/.next/server/app/page.js:840:26)
[08:21:51]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[08:21:51]     at F (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:17:142)
[08:21:51]     at S (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:21:345)
[08:21:51]     at Object.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:23:62)
[08:21:51]     at JSON.parse (<anonymous>)
[08:21:51]     at E (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:16:53)
[08:21:51]     at c (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:26:270)
[08:21:51] 
[08:21:51] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[08:21:51] ReferenceError: document is not defined
[08:21:51]     at 48357 (/vercel/path0/.next/server/chunks/550.js:186369:33)
[08:21:51]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[08:21:51]     at 32341 (/vercel/path0/.next/server/app/page.js:840:26)
[08:21:51]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[08:21:51]     at F (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:17:142)
[08:21:51]     at S (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:21:345)
[08:21:51]     at Object.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:23:62)
[08:21:51]     at JSON.parse (<anonymous>)
[08:21:51]     at E (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:16:53)
[08:21:51]     at c (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:26:270)
[08:21:51] info  - Generating static pages (4/4)
[08:21:51] 
[08:21:51] > Export encountered errors on following paths:
[08:21:51] 	/page: /
[08:21:51] error Command failed with exit code 1.
[08:21:51] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[08:21:51] Error: Command "yarn run build" exited with 1
[08:21:51] Deployment completed
[08:21:51] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

Eu atualmente não estou perto do pc, mas tu deve conseguir testar localmente rodando a build pra ver se rola algum erro.

2023-05-04 17:25 UTC, barbosadev commented
Resolvido @Nick-Gabe :D

2023-05-05 01:15 UTC, Nick-Gabe commented
Adorei, ficou muito bom, mas tenho alguns pedidos uahsuahs
- Poderia fazer ele um pouco maior? Testei no devtools aqui e 100x100 me parece um bom valor pro svg
- No mobile e tablet, ao invés de fixed, poderia deixar ele como absoluto pra não ficar na tela durante o scroll? S]o no desktop eu acho que não afeta muito.

2023-05-05 01:43 UTC, Nick-Gabe requested changes

2023-05-05 01:43 UTC, Nick-Gabe commented on src/app/components/GithubCorners/GithubCorners.tsx
> +export default GithubCorners;
Unma dúvida, será que não seria possível importar o componente direto como eles mostram na documentação? Assim talvez não seria necessário fazer isso rodar client side
```js
import GitHubCorners from '@uiw/react-github-corners';

function Demo() {
  return (
    <GitHubCorners
      position="left"
      href="https://github.com/uiwjs/react-github-corners"
    />
  )
}
```

2023-05-13 23:12 UTC, Nick-Gabe commented
Muito obrigado pela contribuição ❤️ , mas vou fechar este PR pra implementar as mudanças que falei, eu ia fazer merge deste mas está com alguns conflitos que eu não conseguiria resolver por aqui.

2023-05-13 23:12 UTC, closed without merging