Add antd pagination component for posts view
Nick-Gabe/nick-tech-posts pull request #20
Opened 2023-05-04 21:29 UTC by datsfilipe

**Features:**
- Pagination component;
- Added some styles to match page style using `ConfigProvider` from "antd" package.

**Things to consider:**
- Maybe the added styles are not needed;
- Maybe the `ConfigProvider` should be added in the app file for global customization of `antd` components and not just `Pagination`;
- Maybe you have some other thoughts about it 👀.

I think that's it!

2023-05-05 01:49 UTC, Nick-Gabe requested changes
Muito obrigado pela contribuição Felipe, curti demais, só deixei alguns comentários aqui. 😉

2023-05-05 01:49 UTC, Nick-Gabe commented on src/app/components/Posts/PostPages.tsx
> +    >
Isso é ótimo! Eu estava fazendo os overrides de cores diretamente via css mas acho que isso é uma solução bem mais elegante hahaha 😂

2023-05-05 01:49 UTC, Nick-Gabe commented on src/app/components/Posts/PostPages.tsx
> +      )}
Atualmente tem algo específico acontecendo pra ele precisar ser renderizado de dentro de um parser? Não me parece necessário

2023-05-05 09:28 UTC, datsfilipe commented on src/app/components/Posts/PostPages.tsx
> +    >
É a solução recomendada na lib aparentemente, só fiquei na dúvida se adicionava no componente ou no app.

2023-05-05 09:35 UTC, datsfilipe commented on src/app/components/Posts/PostPages.tsx
> +      )}
Eu estava fazendo outra coisa antes e esqueci de remover aparentemente, removi agr no penúltimo commit.

2023-05-06 03:40 UTC, Nick-Gabe commented on src/app/components/Posts/PostPages.tsx
> +    >
Desculpe a demora, mas pode fazer no app sim, acho que isso é um ótimo padrao pra se manter globalmente

2023-05-06 06:01 UTC, datsfilipe commented on src/app/components/Posts/PostPages.tsx
> +    >
Adicionei em conjunto com o componente `Providers` para poder fazer uso da diretiva "use client" (necessária).

2023-05-06 16:59 UTC, Nick-Gabe commented
Vou baixar e testar localmente pra ver a aparência, mas me parece que tá tudo certo :D

2023-05-07 01:44 UTC, Nick-Gabe requested changes
Fiz uns comentários por um bug que encontrei, mas deixei tudo prontinho, só copiar e colar :)
Não mandei eu mesmo pq como tá no seu fork eu não tenho acesso

2023-05-07 01:44 UTC, Nick-Gabe commented on src/app/components/Posts/PostPages.tsx
> +
tu pode criar um useEffect e useState aqui, acho que fica mais limpo do que fazer inline
```ts
const [posts, setPosts] = useState<Post[]>([]);

useEffect(() => {
  setPosts(props.posts.slice((currentPage - 1) * postsPerPage, currentPage * postsPerPage))
}, [currentPage, props.posts]);
```

2023-05-07 01:44 UTC, Nick-Gabe commented on src/app/components/Posts/PostPages.tsx
> +        ))}
Aqui como tu vai ter o useState, tu pode substituir por:
```ts
{posts.map((post) => (
  <PostCard key={post.id} post={post} search={props.search} />
))}
```

2023-05-07 01:44 UTC, Nick-Gabe commented on src/app/components/Posts/PostPages.tsx
>  }
pode remover essa parte, aí a gente faz ela assim que a chamada pra api é feita, economiza processamento pq roda uma única vez.

No arquivo `Posts/Posts.tsx` tu vai botar o seguinte:
```ts
import axios from "axios";
import { useEffect, useState } from "react";
import { Post } from "../PostCard/postCardTypes";
import { PostsProps } from "./postsTypes";
import { Loading } from "../Loading/Loading";
import { NoPostsFound } from "./NoPostsFound";
import { PostPages } from "./PostPages";

const sortByDate = (a: Post, b: Post) => {
  return new Date(a.date) < new Date(b.date) ? 1 : -1
}

export const Posts = (props: PostsProps) => {
  const { loading, setLoading } = props;
  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {
    axios.get(`/api/posts?search=${props.search}`)
      .then((response) => {
        const postsSortedByDate = response.data.sort(sortByDate);
        setPosts(postsSortedByDate);
        setLoading(false);
      })
  }, [props.search, setLoading])

  if (loading) return <Loading />
  if (posts.length === 0) return <NoPostsFound />

  return <PostPages posts={posts} search={props.search} />
}
```

2023-05-07 01:44 UTC, Nick-Gabe commented on src/app/components/Posts/PostPages.tsx
> +const postsPerPage = 12;
Pode diminuir pra 9, achei que 12 ficou com muitos elementos

2023-05-07 01:44 UTC, Nick-Gabe requested changes
Fiz uns comentários por um bug que encontrei, mas deixei tudo prontinho, só copiar e colar :)
Não mandei eu mesmo pq como tá no seu fork eu não tenho acesso

2023-05-07 02:24 UTC, datsfilipe commented
Tudo concluído, acredito eu.

2023-05-07 16:11 UTC, Nick-Gabe commented
Mandou bem @datsfilipe! Muito obrigado pela paciência ❤️

2023-05-07 16:11 UTC, Nick-Gabe approved these changes
Mandou bem @datsfilipe, muito obrigado pela paciência! ❤️

2023-05-07 16:11 UTC, merged